# Generated by Django 5.2.3 on 2025-06-21 04:41

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto de introdução do formulário', verbose_name='Introdução')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Texto exibido após envio do formulário', verbose_name='Texto de agradecimento')),
                ('background_color', models.CharField(default='#ffffff', help_text='Código hexadecimal da cor (ex: #ffffff)', max_length=7, verbose_name='Cor de fundo')),
                ('primary_color', models.CharField(default='#2A5E2C', help_text='Cor dos botões e elementos principais', max_length=7, verbose_name='Cor primária')),
                ('show_progress_bar', models.BooleanField(default=True, verbose_name='Mostrar barra de progresso')),
                ('form_title', models.CharField(default='Formulário de Inscrição', max_length=255, verbose_name='Título do formulário')),
                ('form_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo/Imagem de boas-vindas')),
                ('thank_you_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de agradecimento')),
            ],
            options={
                'verbose_name': 'Formulário Personalizado',
                'verbose_name_plural': 'Formulários Personalizados',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormularioField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('field_type', models.CharField(choices=[('singleline', 'Texto simples'), ('multiline', 'Texto longo (textarea)'), ('email', 'Email'), ('number', 'Número'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes múltiplos'), ('dropdown', 'Lista suspensa'), ('multiselect', 'Seleção múltipla'), ('radio', 'Botões de opção'), ('date', 'Data'), ('datetime', 'Data e hora'), ('hidden', 'Campo oculto'), ('cpf', 'CPF'), ('telefone', 'Telefone'), ('senha', 'Senha')], default='singleline', max_length=16, verbose_name='Tipo do campo')),
                ('choices', models.TextField(blank=True, help_text='Necessário para dropdown, checkboxes, etc. Uma opção por linha.', verbose_name='Opções')),
                ('default_value', models.CharField(blank=True, help_text='Valor pré-preenchido (opcional)', max_length=255, verbose_name='Valor padrão')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de exemplo no campo', max_length=255, verbose_name='Placeholder')),
                ('help_text_field', models.CharField(blank=True, help_text='Texto explicativo abaixo do campo', max_length=255, verbose_name='Texto de ajuda')),
                ('section_title', models.CharField(blank=True, help_text='Título grande acima da pergunta', max_length=255, verbose_name='Título da seção')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do campo', verbose_name='Ordem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.formulariopage')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormularioSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(verbose_name='Dados do formulário')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formulariopage')),
            ],
            options={
                'verbose_name': 'Submissão do Formulário',
                'verbose_name_plural': 'Submissões do Formulário',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
