# Generated by Django 5.2.3 on 2025-06-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_formulariopage_background_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariopage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Imagem de fundo para o formulário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de fundo'),
        ),
    ]
